import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`flex justify-center items-center h-screen`}>
        <h1 className={`text-4xl`}>
          Welcome to{" "}
          <a
            className={`text-blue-500 hover:underline`}
            href="https://nextjs.org"
          >
            Next.js!
          </a>
        </h1>
      </main>
    </>
  );
}
